<!doctype html><html><head><meta charset=UTF-8><meta content="IE=edge" http-equiv=X-UA-Compatible><meta content="width=device-width,initial-scale=1.0" name=viewport><title> Flask-SQLAlchemy, psycopg2 and passwords with special characters </title><link href=https://rneto.net/fonts.css rel=stylesheet><link title="Rui Neto" href=https://rneto.net/atom.xml rel=alternate type=application/atom+xml><link href=https://rneto.net/theme/light.css rel=stylesheet><link href=https://rneto.net/main.css media=screen rel=stylesheet><body><div class=content><header><div class=main><a href=https://rneto.net>Rui Neto</a></div><nav><a style="margin-left: 0.7em" href=/posts>/posts</a><a style="margin-left: 0.7em" href=https://github.com/rnetonet/ target=blank>/github</a><a style="margin-left: 0.7em" href=https://twitter.com/rnetonet/ target=blank>/twitter</a></nav></header><main><article><div class=title><div class=page-header>Flask-SQLAlchemy, psycopg2 and passwords with special characters<span style="font-size: 1.6em" class=primary-color>.</span></div><div class=meta>22/07/2024</div></div><h1>TOC</h1><ul><li><a href=https://rneto.net/posts/20240722-psycopg2-password-encoding/#flask-sqlalchemy-psycopg2-and-passwords-with-special-characters>Flask-SQLAlchemy, psycopg2 and passwords with special characters</a> <ul><li><a href=https://rneto.net/posts/20240722-psycopg2-password-encoding/#context>Context</a><li><a href=https://rneto.net/posts/20240722-psycopg2-password-encoding/#fixing>Fixing</a><li><a href=https://rneto.net/posts/20240722-psycopg2-password-encoding/#references>References</a></ul></ul><section class=body><h2 id=flask-sqlalchemy-psycopg2-and-passwords-with-special-characters>Flask-SQLAlchemy, psycopg2 and passwords with special characters</h2><h3 id=context>Context</h3><p>After spending a lot of time debugging a Flask-SQLAlchemy connection error to a PostgreSQL database, I found out the root cause was special characters in the database password. Specifically, the password contained the <code>@</code> symbol.<p>The <strong>psycopg2</strong> error message is not very helpful either, as it displays a generic error like:<pre class=language-bash data-lang=bash style=background-color:#ffffff;color:#323232;><code class=language-bash data-lang=bash><span>UnicodeDecodeError: </span><span style=color:#183691;>'utf-8'</span><span> codec can</span><span style=color:#183691;>'t decode byte 0xd6 in position 61: invalid continuation byte
</span></code></pre><h3 id=fixing>Fixing</h3><p>To fix it, you should escape the password using <strong>urllib.parse</strong>:<pre class=language-python data-lang=python style=background-color:#ffffff;color:#323232;><code class=language-python data-lang=python><span style=font-weight:bold;color:#a71d5d;>from </span><span>urllib </span><span style=font-weight:bold;color:#a71d5d;>import </span><span>parse
</span><span style=font-weight:bold;color:#a71d5d;>import </span><span>psycopg2
</span><span>
</span><span>dsn </span><span style=font-weight:bold;color:#a71d5d;>= fr</span><span style=color:#183691;>"postgresql://souser:</span><span>{parse.quote(password)}</span><span style=color:#183691;>@localhost/test"
</span></code></pre><h3 id=references>References</h3><ul><li>https://stackoverflow.com/a/77193560</ul></section></article></main></div>